-- +goose Up
CREATE TABLE view_options (
    user_id VARCHAR(36) PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    channel_count INT NOT NULL DEFAULT 0,
    tittle BOOLEAN NOT NULL DEFAULT FALSE,
    about BOOLEAN NOT NULL DEFAULT FALSE,
    channel_id BOOLEAN NOT NULL DEFAULT FALSE,
    channel_date BOOLEAN NOT NULL DEFAULT FALSE,
    participants_count BOOLEAN NOT NULL DEFAULT FALSE,
    photo BOOLEAN NOT NULL DEFAULT FALSE,
    message_count INT NOT NULL DEFAULT 0,
    message_id BOOLEAN NOT NULL DEFAULT FALSE,
    views BOOLEAN NOT NULL DEFAULT FALSE,
    post_date BOOLEAN NOT NULL DEFAULT FALSE,
    reactions_count BOOLEAN NOT NULL DEFAULT FALSE,
    reactions BOOLEAN NOT NULL DEFAULT FALSE
);