// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

type User struct {
	UserID      string `json:"user_id"`
	Username    string `json:"username"`
	PhoneNumber string `json:"phone_number"`
}

type ViewOption struct {
	UserID            string `json:"user_id"`
	ChannelCount      int    `json:"channel_count"`
	Tittle            bool   `json:"tittle"`
	About             bool   `json:"about"`
	ChannelID         bool   `json:"channel_id"`
	ChannelDate       bool   `json:"channel_date"`
	ParticipantsCount bool   `json:"participants_count"`
	Photo             bool   `json:"photo"`
	MessageCount      int    `json:"message_count"`
	MessageID         bool   `json:"message_id"`
	Views             bool   `json:"views"`
	PostDate          bool   `json:"post_date"`
	ReactionsCount    bool   `json:"reactions_count"`
	Reactions         bool   `json:"reactions"`
}
