// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateViewOptions(ctx context.Context, arg CreateViewOptionsParams) error
	DeleteUser(ctx context.Context, userID string) error
	DeleteViewOptions(ctx context.Context, userID string) error
	GetUser(ctx context.Context, userID string) (User, error)
	GetViewOptions(ctx context.Context, userID string) (ViewOption, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateViewOptions(ctx context.Context, arg UpdateViewOptionsParams) error
}

var _ Querier = (*Queries)(nil)
